spring.application.name=payment-engine

# Configuracoes de Conexao com o Banco de Dados PostgreSQL

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracoes do Hibernate

spring.jpa.hibernate.ddl-auto=${DDL_AUTO}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuracoes de Conexao com o RabbitMQ

spring.rabbitmq.host=${RABBIT_HOST}
spring.rabbitmq.port=${RABBIT_PORT}
spring.rabbitmq.username=${RABBIT_USER}
spring.rabbitmq.password=${RABBIT_PASSWORD}

# Configuracao da Chave do Stripe

stripe.api.key=${STRIPE_API_KEY}
spring.security.user.name=${SECURITY_USER}
spring.security.user.password=${SECURITY_PASSWORD}

server.port=${SERVER_PORT}
